### PR TITLE
[MSHARED-939] Remove Apache Ivy from dependency

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by elharo** [comment]
checking ci here: https://builds.apache.org/job/maven-box/job/maven-script-interpreter/job/ty/

I'd love to get rid of this if we can.

**Comment by slawekjaranowski** [comment]
I hope - we can, As I wrote in in issue all test in maven-invoker-plugin pass without it.

I think that we can add another dependency to test by adding dependency in scope test and use addTestClassPath at maven-invoker-plugin or add dependency to plugin configuration.

Mixed dependency resolving system may not be good way. 
So we shouldn't provided such functionality by default for all users.

I'm not sure if it works - we don't any tests for confirmation.

**Comment by slachiewicz** [comment]
@hboutemy what is your opinion?

**Comment by elharo** [comment]
CI passed.

**Comment by jira-importer** [comment]
Resolve #150

**Pull request closed without merging**
