### PR TITLE
upgrade to parent 39

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by slachiewicz** [comment]
Missing Jira

**Comment by olamy** [comment]
> Missing Jira

LOL so many dependabot PRs didn't have any Jira :P

**Comment by slachiewicz** [comment]
https://issues.apache.org/jira/browse/MSHARED-1157

**Comment by olamy** [comment]
I updated the title of the jira if this help

**Pull request merged**
