### PR TITLE
remove unused dependency

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
`slf4j-simple` is used during test running, without it we have info: 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

and of course logging is not show

**Comment by slawekjaranowski** [comment]
If we don't see logs during test better way is having `slf4j-simple` and configure it to display certain `loglevel`, eg `error`.

**Comment by elharo** [comment]
If this is just to suppress the error messages, then we should change it to slf4j-nop. Generally one doesn't want logs from src/java printed during tests. Only failing tests should generate output. Otherwise the needle you want to see gets lost in a haystack of log junk.

**Comment by slachiewicz** [comment]
-1 we need this dependency

**Pull request closed without merging**
